name: Code quality

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  quality:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze --write=flutter_analyze.log
      - name: Riverpod lint
        run: dart run custom_lint --format=json > custom_lint.log
      - if: ${{ !cancelled() }}
        uses: yorifuji/flutter-analyze-commenter@v1
        with:
          analyze-log: flutter_analyze.log
          custom-lint-log: custom_lint.log